pruebasapp/pollos/urls.py
from django.urls import path

from . import views

app_name = 'pollos'
urlpatterns = [
    # ex: /pollos/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /pollos/5/
    path('<int:pk>/detail/',
         views.DetailView.as_view(), name='detail'),
    # ex: /pollos/5/results
    path('<int:pk>/results/',
         views.ResultView.as_view(), name='results'),
    # ex: /pollos/5/vote
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

pruebasapp/pruebasapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pollos/', include("pollos.urls"))
]

pruebasapp/pollos/models.py
from random import choice
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pruebasapp/pollos/views.py
# Create your views here.
from multiprocessing import context
from pyexpat import model
from re import template
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, choice


# def index(request):
#     latest_question_list = Question.objects.all()
#     return render(request, 'pollos/index.html', {
#         "latest_question_list": latest_question_list
#     })


# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'pollos/detail.html', {
#         'question': question
#     })


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'pollos/results.html', {
#         'question': question
#     })

class IndexView(generic.ListView):
    template_name = 'pollos/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the las five published questions"""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'pollos/detail.html'

    def get_queryset(self):
        """
        Excludes any question that aren't published yet
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultView(generic.DetailView):
    model = Question
    template_name = 'pollos/detail.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, choice.DoesNotExist):
        return render(request, 'pollos/detail.html', {
            'question': question,
            'error_message': 'No elegiste una respuesta'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('pollos:results', args=(question.id,)))

pruebasapp/pollos/templates/pollos/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='stylesheet' href='{% static 'pollos/style.css' %}'>
    <link rel='stylesheet' href='{% static 'pollos/detail.css' %}'>
    <title>{{ question.question_text }}</title>
</head>
<body>
    <form action="{% url 'pollos:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input
                    type='radio'
                    name='choice'
                    id='choice{{ forloop.counter }}'
                    value='{{choice.id}}'
                >
                <label for='choice{{ forloop.counter }}'>
                    {{ choice.choice_text }}
                </label>
                <br>
            {% endfor %}
        </fieldset>
        <input type='submit' value='votar'>
    </form>
</body>
</html>


{% comment %} <h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> {% endcomment %}

pruebasapp/pollos/templates/pollos/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel='stylesheet' href='{% static 'pollos/reset.css' %}'>
    <link rel='stylesheet' href='{% static 'pollos/style.css' %}'>
    <title>Projet Django App</title>
</head>
<body>
    <header>
        <h1>Projet Django App</h1>
    </header>
    <main>
        {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li>
                    <a href=" {% url 'pollos:detail' question.id  %} ">
                        {{ question.question_text}}
                    </a>
                </li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No pollos are available.</p>
        {% endif %}
    </main>
    <footer>
        <a href="https://google.com">Pruebas</a>
        <a href="#">Contacto</a>
        <a href="#">¿Quien eres?</a>
        <a href="#">Políticas de privacidad</a>
        <a href="#">Términos y condiciones</a>
    </footer>
</body>
</html>


{% comment %} {% load static %}
<link rel='stylesheet' href='{% static 'pollos/style.css' %}'>

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'pollos:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No pollos are available.</p>
{% endif %}  {% endcomment %}

pruebasapp/pollos/templates/pollos/results.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'pollos:detail' question.id %}">¿Te gustaría votar de nuevo</a>